# Generated by Django 5.1.3 on 2025-05-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_folder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FolderShare',
        ),
    ]
