# Generated by Django 5.1.3 on 2025-06-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_folder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
